# reference file for mapping
reference: "/storage/mi/tomw97/Data/AppliedSeqAn/reference/reference.FASTA"
# file containg samples with paired end reads (with given formating)
samples: "/home/mi/tomw97/Schreibtisch/Development/AppliedSequenceAnalysis/Data/samples.tsv"
# folder to save results to
results: "/home/mi/tomw97/Schreibtisch/Development/AppliedSequenceAnalysis/Task2/results"
# script that calculates the rpk from a stat file
rpk_script: "/home/mi/tomw97/Schreibtisch/Development/AppliedSequenceAnalysis/Task2/workflows/scripts/calc_rpk.py"