from pathlib import Path
import pandas as pd

configfile: Path.cwd() / ".." / "config" / "config.yaml"

# read config settings
sample_files = Path(config["samples"])
reference = Path(config["reference"])
ref_base = str(reference.parent / reference.stem)
result_dir = Path(config["results"])
adapter_seqs = Path(config["adapter"])
param_min_frag_len = config["min_frag_length"]
param_max_frag_len = config["max_frag_length"]

# python script for rpk calculation
rpk_script = Path.cwd() / "scripts" / "calc_rpk.py"

# read file containing sample paths
samples = pd.read_csv(sample_files, index_col ="sample", sep='\t')

rule all:
    input:
        expand(result_dir / "stats" / "{sample}.stats_aug", sample=list(samples.index)),
        result_dir / "qc_files" / "final_qc_report.html"

rule aug_stats:
    input:
        result_dir / "stats" / "{sample}.stats"
    output:
        result_dir / "stats" / "{sample}.stats_aug"
    shell:
        "python3 {rpk_script} {input}"

include: Path.cwd() / "rules" / "samtools.smk"

include: Path.cwd() / "rules" / "bowtie.smk"

include: Path.cwd() / "rules" / "qc.smk"