# file containing samples with paired end reads (and potentially Oxford Nanopore Reads)
# sample  fq1 fq2 (ONT)
# <NAME>  <PATH_TO_FASTQ1>  <PATH_TO_FASTQ2>  (<PATH_TO_ONT>)
# ... ... ... ...
# Note: ONT files are optional - if none are available leave out the corresponding column
#       This will set 'ONT_correction' to 'False'
samples: "/storage/mi/tomw97/Development/AppliedSequenceAnalysis/Data/final_samples_without_ONT.tsv"

# Enables/Disables assembly correction with ONT data (ONT reads have to be provided in 'samples.tsv')
ONT_correction: True

# folder to save results to
results: "/storage/mi/tomw97/Data/AppliedSeqAn/Final_Project/results_without_ONT"

# maximum number of threads
# Note: some rules have an upper bound for their thread usage
max_threads: 30

# fasta file containing adapter seqs
# If left empty a default file with commonly used adapters will be used.
adapter: ""

# directory containing the DB files for contamination identification with kraken2
kraken_db: "/storage/mi/tomw97/Data/AppliedSeqAn/reference/kraken_db"

# fasta file containing a contamination database (for decontamination of Illumina reads)
# use 'snakemake --use-conda screen' to get a taxonomic screening
# Note: leaving this empty is equal to setting 'skip_decontamination' to 'True'
contamination_db: ""

# Phylogenetic Blacklisting
# file containing sample names (corresponding to the 'samples' input) - 1 sample name per row
# If no blacklisting should occur just pass no file here, e.g. ""
blacklist: ""
blacklist_core_genome: True # Start blacklisting at core genome calculation (instead of at tree calculation)

# trimmomatic settings
trimmomatic:
  mismatches: 2         # number of allowed mismatches for adapter identification
  score_threshold: 30   # threshold needs to be reached for clipping to happen

# core genome calculation settings
roary:
  threshold: 70         # threshold for core genome calculation (percentage of genomes containing a gene for it to be considered 'core')

# phylogenetic model
RAxML:
  model: "GAMMA"        # 'GAMMA' or 'CAT'
  ML_freq: False        # use maximum likelihood estimate for base frequencies instead of empirical method
  iv_sites: False       # enable estimate of proportion of invariable sites
  ASC: False            # enable correction of likelihood regarding ascertainment bias (doesn't work if 'iv_sites' is 'True')

MLST:
  species: ""           # optional species to search with MLST (if left empty this will be determined automatically)

# Skipping
skip:
  # Preprocessing
  trimming_Illumina: False
  trimming_ONT: False
  decontamination: True
  coverage_normalization: False
  # Quality Control
  fastQC: False      # Illumina QC
  nanoplot: False    # ONT QC
  # Database Screening
  MLST: False
  CARD: False
  VFDB: False
  PlasmidFinder: False