from pathlib import Path
import pandas as pd

configfile: Path("config") / "config.yaml"

# read config settings
sample_files = Path(config["samples"])
reference = Path(config["reference"])
result_dir = Path(config["results"])
adapter_seqs = Path(config["adapter"])

# python script for rpk calculation
rpk_script = str(Path("scripts") / "calc_rpk.py")

# read file containing sample paths
samples = pd.read_csv(sample_files, index_col ="sample", sep='\t')

rule all:
    input:
        expand(result_dir / "stats" / "{sample}.stats_aug", sample=list(samples.index)),
        result_dir / "qc_files" / "final_qc_report.html"

rule aug_stats:
    input:
        result_dir / "stats" / "{sample}.stats"
    output:
        result_dir / "stats" / "{sample}.stats_aug"
    script:
        rpk_script

include: Path("rules") / "samtools.smk"

include: Path("rules") / "bowtie.smk"

include: Path("rules") / "qc.smk"