# reference file for mapping
reference: "/storage/mi/tomw97/Data/AppliedSeqAn/reference/reference.FASTA"
# file containg samples with paired end reads (with given formating)
samples: "/home/mi/tomw97/Schreibtisch/Development/AppliedSequenceAnalysis/Data/samples.tsv"
# folder to save results to
results: "/home/mi/tomw97/Schreibtisch/Development/AppliedSequenceAnalysis/Task3/results"
# fasta file containing adapter seqs
adapter: "resources/TruSeq2-PE.fa"
# bowtie2 settings
bowtie2_mapping:
  X: 500  # maximum fragment length
  I: 0    # minimum fragment length
# skip settings
skip_qualimap: False
skip_trimming: False
skip_fastQC: False